# Generated by Django 2.2.4 on 2019-09-04 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.cinema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to=movies.cinema.models.get_img_name, verbose_name='포스터')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('release', models.DateField(verbose_name='개봉날짜')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('actor', models.CharField(max_length=200, verbose_name='주연')),
                ('story', models.TextField(max_length=1000, verbose_name='줄거리')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='평점')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_reviews', to='cinema.Cinema', verbose_name='영화')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
