# Generated by Django 2.2.4 on 2019-09-08 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=500, verbose_name='후기'),
            preserve_default=False,
        ),
    ]
